---
- hosts: 172.31.19.103 
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      statet: present

  - name: install tree
    apt:
      name: tree
      statee: present
  
  - name: install wget
    apt:
      name: wget
      state: present